config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get '/signup', to: 'users#new'

  get 'static_pages/home'

  get '/help', to: 'static_pages#help'

  get '/about', to: 'static_pages#about'

  get '/contact', to: 'static_pages#contact'  

  root 'static_pages#home'

  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :account_activations, only: [:edit]
  resources :users
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
end

app/views/layouts/_header.html.erb
<nav class="myNav">
  <div class="container-fluid">
    <div class="row">

      <div class="col-lg-4 col-md-5 hidden-sm hidden-xs">
        <ul class="home">
          <li><a href="/"><i class="fa fa-home" aria-hidden="true"></i> Home</a></li>
          <% if logged_in? %>
              <li><a href="#"><i class="fa fa-bell-o" aria-hidden="true"></i> Notifications</a></li>
              <li><a href="#"><i class="fa fa-comments-o" aria-hidden="true"></i> Messages</a></li>
          <% end %>
          <li><a href="/about">About</a></li>
        </ul>
      </div>

      <div class="hidden-lg hidden-md col-sm-5 hidden-xs">
        <ul class="home">
          <li><a href="/"><i class="fa fa-home" aria-hidden="true"></i></a></li>
          <% if logged_in? %>
              <li><a href="#"><i class="fa fa-bell-o" aria-hidden="true"></i></a></li>
              <li><a href="#"><i class="fa fa-comments-o" aria-hidden="true"></i></a></li>
          <% end %>
          <li><a href="/about">About</a></li>
        </ul>
      </div>

      <div class="col-lg-4 col-md-2 col-sm-2 col-xs-8">
        <span id="title"><a href="/"><i class="fa fa-twitter" aria-hidden="true"></i> Twitter</a></span>
      </div>

      <% if logged_in? %>
        <div class="col-lg-4 col-md-5 hidden-sm hidden-xs">
          <ul class="login">
            <li>
              <a href="#" class="drop_toggle"><%= gravatar_for current_user, size: 25 %><%= current_user.name %></a>
              <div class="drop">
                <ul class="content">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <!--<li class="divider"></li>-->
                  <li>
                    <%= link_to "Log out", logout_path, method: "delete" %>
                  </li>
                </ul>
              </div>
            </li>
            <li><%= link_to "Users", users_path %></li>
          </ul>
        </div>
        <div class="hidden-lg hidden-md col-sm-5 hidden-xs">
          <ul class="login">
            <li>
              <a href="#" class="drop_toggle"><%= gravatar_for current_user, size: 25 %><%= current_user.name %></a>
              <div class="drop">
                <ul class="content">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <!--<li class="divider"></li>-->
                  <li>
                    <%= link_to "Log out", logout_path, method: "delete" %>
                  </li>
                </ul>
              </div>
            </li>
            <li><%= link_to "Users", users_path %></li>
          </ul>
        </div>
      <% else %>
        <div class="col-lg-4 col-md-5 col-sm-5 hidden-xs">
          <ul class="login">
            <li><a href="/login"><i class="fa fa-sign-in" aria-hidden="true"></i> Login</a></li>
            <li><a href="/signup"><i class="fa fa-user-circle" aria-hidden="true"></i> Sign Up</a></li>
          </ul>
        </div>
      <% end %>

      <div class="hidden-lg hidden-md hidden-sm col-xs-4">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar" onclick="openNav()">
          <span style="background-color: #0084b4;" class="icon-bar"></span>
          <span style="background-color: #0084b4;" class="icon-bar"></span>
          <span style="background-color: #0084b4;" class="icon-bar"></span>
        </button>
      </div>

    </div>
  </div>
</nav>

<!-- For xs -->
<div id="myNav" class="overlay">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times</a>
  <div class="overlay-content">
    <ul class="xs-nav">
      <li><a href="#"><i class="fa fa-home" aria-hidden="true"></i> Home</a></li>
      <% if logged_in? %>
          <li><a href="#"><i class="fa fa-bell-o" aria-hidden="true"></i> Notifications</a></li>
          <li><a href="#"><i class="fa fa-comments-o" aria-hidden="true"></i> Messages</a></li>
          <li><a href="/about">About</a></li>
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Settings", '#' %></li>
          <li><%= link_to "Log out", logout_path, method: "delete" %></li>
      <% else %>
          <li><a href="/login"><i class="fa fa-sign-in" aria-hidden="true"></i> Login</a></li>
          <li><a href="/signup"><i class="fa fa-user-circle" aria-hidden="true"></i> Signup</a></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title))%></title>
    <meta name="author" content="Rishabh Khatri">
    <meta name="description" content="IIITD's microblogging website">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <script src="https://use.fontawesome.com/8bb2c5e006.js"></script>

    <!-- Google Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Playfair+Display' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,300' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Abril+Fatface' rel='stylesheet' type='text/css'>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>


  <%= render 'layouts/header' %>
  	<div class="container-fluid" style="padding: 20px;margin-top: 30px;">
      <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
  		<%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if
      Rails.env.development?%>
  	</div>
  </body>
</html>